# Build, package and clean Fatiando
PY=python
PIP=pip
NOSE=nosetests

# To upload to PyPI run:
# python setup.py sdist --formats=zip,gztar upload

.PHONY: help
help:
	@echo "Commands:"
	@echo ""
	@echo "    build         build the extension modules inplace"
	@echo "    docs          build the html documentation"
	@echo "    docs-pdf      build the pdf documentation"
	@echo "    test          run the test suite (including doctests)"
	@echo "    deps          installs development requirements"
	@echo "    package       create source distributions"
	@echo "    clean         clean up"
	@echo ""

# BUILD EXTENSION MODULES
.PHONY: build
build:
	$(PY) setup.py build_ext --inplace

# BUILD THE DOCS
.PHONY: docs
docs: clean
	cd doc; make html

.PHONY: docs-pdf
docs-pdf: clean
	cd doc; make latexpdf

# RUN ALL TESTS
.PHONY: test
test:
	$(NOSE) fatiando

# INSTALL THE DEPENDENCIES
.PHONY: deps
deps: requires.txt
	$(PIP) install -r $<

# MAKE A SOURCE DISTRIBUTION
.PHONY: package
package: docs
	$(PY) setup.py sdist --formats=zip,gztar

# CLEAN THINGS UP
.PHONY: clean
clean:
	find . -name "*.so" -exec rm -v {} \;
	find "fatiando" -name "*.c" -exec rm -v {} \;
	find . -name "*.pyc" -exec rm -v {} \;
	rm -rvf build dist MANIFEST
	# Trash generated by the doctests
	rm -rvf mydata.txt mylogfile.log
	# The logo image fetched by the cookbook recipes
	rm -rvf logo.png cookbook/logo.png

.PHONY: clean-docs
clean-docs:
	# Clean the docs as well
	cd doc; make clean
